build:
	javac cli/*.java db/db_op/*.java db/file_op/*.java db/user_op/*.java db/*.java *.java

run:
	java -cp .:ojdbc10-19.24.0.0.jar CSCI3170Proj

clean:
	rm cli/*.class
	rm db/db_op/*.class
	rm db/file_op/*.class
	rm db/user_op/*.class
	rm db/*.class
	rm *.class